FROM python:3.11

WORKDIR /opt/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY etl/ etl/

RUN  pip install --no-cache-dir --upgrade pip \
     && pip install -r etl/requirements.txt

ENTRYPOINT ["python3", "etl/main.py"]